### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Evgeny1103** [lintest/GraphViz1C#2]
Приветствую! 
Получил ошибку  в VS2022

	CMake Error at C:\Users\evgen\source\repos\GraphViz1C\CMakeLists.txt:85 (add_subdirectory):
  add_subdirectory given source "./GraphViz" which is not an existing
  directory.	GraphViz1c	C:\Users\evgen\source\repos\GraphViz1C\CMakeLists.txt	85
  
Прошу Вашего совета. 
С уважением,
Евгений

**Comment by lintest** [comment]
Для сборки нужно установить все зависимости, как это делается в файле
https://github.com/lintest/GraphViz1C/blob/develop/appveyor.yml

**Comment by Evgeny1103** [comment]
Очень оперативно. Огромное спасибо!
